export const getCountries = () => {
    return [
        {code: "ar", name: "Argentina"},
        {code: "am", name: "Armenia"},
        {code: "au", name: "Australia"},
        {code: "at", name: "Austria"},
        {code: "by", name: "Belarus"},
        {code: "be", name: "Belgium"},
        {code: "bo", name: "Bolivia"},
        {code: "br", name: "Brazil"},
        {code: "bg", name: "Bulgaria"},
        {code: "ca", name: "Canada"},
        {code: "cl", name: "Chile"},
        {code: "cn", name: "China"},
        {code: "co", name: "Colombia"},
        {code: "hr", name: "Croatia"},
        {code: "cz", name: "Czechia"},
        {code: "ec", name: "Ecuador"},
        {code: "eg", name: "Egypt"},
        {code: "fr", name: "France"},
        {code: "de", name: "Germany"},
        {code: "gr", name: "Greece"},
        {code: "hn", name: "Honduras"},
        {code: "hk", name: "Hong Kong"},
        {code: "in", name: "India"},
        {code: "id", name: "Indonesia"},
        {code: "ir", name: "Iran"},
        {code: "ie", name: "Ireland"},
        {code: "il", name: "Israel"},
        {code: "it", name: "Italy"},
        {code: "jp", name: "Japan"},
        {code: "kr", name: "Korea"},
        {code: "mx", name: "Mexico"},
        {code: "nl", name: "Netherlands"},
        {code: "nz", name: "New Zealand"},
        {code: "ni", name: "Nicaragua"},
        {code: "pk", name: "Pakistan"},
        {code: "pa", name: "Panama"},
        {code: "pe", name: "Peru"},
        {code: "pl", name: "Poland"},
        {code: "pt", name: "Portugal"},
        {code: "qa", name: "Qatar"},
        {code: "ro", name: "Romania"},
        {code: "ru", name: "Russia"},
        {code: "sa", name: "Saudi Arabia"},
        {code: "za", name: "South Africa"},
        {code: "es", name: "Spain"},
        {code: "ch", name: "Switzerland"},
        {code: "sy", name: "Syria"},
        {code: "tw", name: "Taiwan"},
        {code: "th", name: "Thailand"},
        {code: "tr", name: "Turkey"},
        {code: "ua", name: "Ukraine"},
        {code: "gb", name: "United Kingdom"},
        {code: "us", name: "United States Of America"},
        {code: "uy", name: "Uruguay"},
        {code: "ve", name: "Venezuela"}
    ];
};

export const getCategories = () => {
    return ["general", "science", "sports", "business", "health", "entertainment", "tech", "politics", "food", "travel"]
};
